//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public Audit()
        {
            this.AuditPackage = new HashSet<AuditPackage>();
        }
    
        public int AuditId { get; set; }
        public System.DateTime DateAudited { get; set; }
        public int DistributionCentreId { get; set; }
        public int EmployeeId { get; set; }
        public int PackageTypeId { get; set; }
    
        public virtual ICollection<AuditPackage> AuditPackage { get; set; }
        public virtual DistributionCentre DistributionCentre { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual StandardPackageType StandardPackageType { get; set; }
    }
}
