//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionCentreStock
    {
        public int PackageTypeId { get; set; }
        public string PackageTypeDescription { get; set; }
        public decimal CostPerPackage { get; set; }
        public int DistributionCentreId { get; set; }
        public string DistributionCenterName { get; set; }
        public Nullable<int> NumberOfPackages { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
    }
}
