//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionCentreLosses
    {
        public Nullable<int> DistributionCentreId { get; set; }
        public string DistributionCenterName { get; set; }
        public Nullable<int> LossRatioNumerator { get; set; }
        public Nullable<int> LossRatioDenominator { get; set; }
        public Nullable<decimal> TotalLossDiscardedValue { get; set; }
    }
}
