//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorActivity
    {
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public int PackageTypeId { get; set; }
        public string PackageTypeDescription { get; set; }
        public Nullable<int> PackageCount { get; set; }
        public Nullable<decimal> TotalPackageValue { get; set; }
    }
}
