//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    
    public enum PackageStatus : int
    {
        InTransit = 1,
        InStock = 2,
        Discarded = 3,
        Distributed = 4,
        Lost = 5
    }
}
