//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageTransit
    {
        public int TransitId { get; set; }
        public int PackageId { get; set; }
        public int SenderCentreId { get; set; }
        public int ReceiverCentreId { get; set; }
        public System.DateTime DateSent { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
    
        public virtual DistributionCentre ReceiverCentre { get; set; }
        public virtual DistributionCentre SenderCentre { get; set; }
        public virtual Package Package { get; set; }

    }
}
