//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<DistributionCentre> DistributionCentre { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<PackageTransit> PackageTransit { get; set; }
        public virtual DbSet<StandardPackageType> StandardPackageType { get; set; }
        public virtual DbSet<AuditPackage> AuditPackage { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
    }
}
