//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENetCareMVC.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueInTransit
    {
        public int SenderDistributionCentreId { get; set; }
        public string SenderDistributionCentreName { get; set; }
        public int ReceiverDistributionCentreId { get; set; }
        public string RecieverDistributionCentreName { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
    }
}
